services:
  db:
    image: mysql:latest
    container_name: casa-real-db
    environment:
      MYSQL_ROOT_PASSWORD: 4CM13v1y
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./ConfiguracionSQL.sql:/docker-entrypoint-initdb.d/ConfiguracionSQL.sql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data: